name: "Update Grant Web Design Application"
description: "This action connects to the Grant Web Design hosting server and updates the application by calling the build install script."
author: "Grant Web Design"
inputs:
  gitFolderLocation:
    description: "The location of the git project on the server."
    required: true
  privateKey:
    description: "The organization GWD_HOSTING_SERVER_KEY secret"
    required: true
  serverAddress:
    description: "The organization GWD_HOSTING_SERVER_ADDRESS secret"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
